language: generic

services:
  - docker

env:
  global:
    - CACHE_DIR: $HOME/.cache/docker
    - GRPC_VER: 1.19.1
    - STABLE_PI_COMMIT: 9f6c1f2
    - STABLE_BMV2_COMMIT: 8c6f852
    - LATEST_PI_COMMIT: "`wget -qO- http://api.github.com/repos/p4lang/PI/commits/master | grep -m1 '\"sha\"' | cut -d '\"' -f4 | cut -c1-7`"
    - LATEST_BMV2_COMMIT: "`wget -qO- http://api.github.com/repos/p4lang/behavioral-model/commits/master | grep -m1 '\"sha\"' | cut -d '\"' -f4 | cut -c1-7`"
    - PI_CONFIGURE_FLAGS: "'--with-proto'"
  matrix:
    - TAGNAME: latest
      PI_COMMIT: $LATEST_PI_COMMIT
      BMV2_COMMIT: $LATEST_BMV2_COMMIT
      BMV2_CONFIGURE_FLAGS: "'--with-pi --disable-elogger --without-nanomsg --without-thrift'"
      TRAVIS_ALLOW_FAILURE: true
    - TAGNAME: latest-no-logging
      PI_COMMIT: $LATEST_PI_COMMIT
      BMV2_COMMIT: $LATEST_BMV2_COMMIT
      BMV2_CONFIGURE_FLAGS: "'--with-pi --disable-elogger --without-nanomsg --without-thrift --disable-logging-macros'"
      TRAVIS_ALLOW_FAILURE: true
    - TAGNAME: stable
      PI_COMMIT: $STABLE_PI_COMMIT
      BMV2_COMMIT: $STABLE_BMV2_COMMIT
      BMV2_CONFIGURE_FLAGS: "'--with-pi --disable-elogger --without-nanomsg --without-thrift'"
      TRAVIS_ALLOW_FAILURE: false
    - TAGNAME: stable-no-logging
      PI_COMMIT: $STABLE_PI_COMMIT
      BMV2_COMMIT: $STABLE_BMV2_COMMIT
      BMV2_CONFIGURE_FLAGS: "'--with-pi --disable-elogger --without-nanomsg --without-thrift --disable-logging-macros'"
      TRAVIS_ALLOW_FAILURE: false

cache:
  directories:
  - $CACHE_DIR

before_install:
  - export LOCAL_RUNTIME_IMAGE=p4mn-$TAGNAME
  - export LOCAL_BUILDER_IMAGE=$LOCAL_RUNTIME_IMAGE-builder
  - export DOCKER_RUNTIME_IMAGE=$DOCKER_REPO:$TAGNAME
  - export DOCKER_BUILDER_IMAGE=$DOCKER_RUNTIME_IMAGE-builder
  - export BUILD_ARGS="--build-arg GRPC_VER=$GRPC_VER --build-arg PI_COMMIT=$PI_COMMIT --build-arg BMV2_COMMIT=$BMV2_COMMIT --build-arg PI_CONFIGURE_FLAGS='$PI_CONFIGURE_FLAGS' --build-arg BMV2_CONFIGURE_FLAGS='$BMV2_CONFIGURE_FLAGS'"

install:
  - docker pull $DOCKER_BUILDER_IMAGE
  - docker pull $DOCKER_RUNTIME_IMAGE

script:
  # Build images. Without eval, build args are not escaped properly.
  - eval "docker build --target builder --cache-from $DOCKER_BUILDER_IMAGE -t $LOCAL_BUILDER_IMAGE $BUILD_ARGS ." || travis_terminate 1
  - eval "docker build --target runtime --cache-from $LOCAL_BUILDER_IMAGE --cache-from $DOCKER_RUNTIME_IMAGE -t $LOCAL_RUNTIME_IMAGE $BUILD_ARGS ." || travis_terminate 1
  # Test that all shared objects are present.
  - docker run --rm --entrypoint simple_switch_grpc $LOCAL_RUNTIME_IMAGE --help
  - docker run --rm --entrypoint mn $LOCAL_RUNTIME_IMAGE --help

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master